name: Deploy to Docker

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/docker-project/WeTiquette
          git pull
          docker build -t wetiquette .
          docker stop WeTiquette
          docker rm WeTiquette
          docker run -d --name WeTiquette wetiquette
