name: Deploy to Docker

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t wetiquette-image .

    - name: Push Docker image
      run: docker push wetiquette-image

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull wetiquette-image
          docker stop WeTiquette
          docker rm WeTiquette
          docker run -d --name WeTiquette wetiquette-image
