name: Deploy to Docker

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup OpenVPN
      uses: dperson/openvpn-client@v1
      with:
        config: ${{ secrets.OVPN_CONFIG }}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/docker-project/WeTiquette
          git pull
          docker build -t wetiquette .
          docker stop wetiquette
          docker rm wetiquette
          docker run -p 3000:3000 -d wetiquette
