name: Deploy to Docker

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup OpenVPN
      uses: dbritto-dev/openvpn3-action@main
      with:
        vpn-client-config: ${{ secrets.OVPN_CONFIG }}
        script: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "
            cd /path/to/your/project
            git pull
            docker build -t wetiquette .
            docker stop WeTiquette
            docker rm WeTiquette
            docker run -d --name WeTiquette wetiquette
          "
